[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.plantuml]
plantuml-cmd="docker run --rm -i think/plantuml"

[preprocessor.presentation-preprocessor]

[output.html]
additional-css = ["assets/mermaid.css"]
additional-js = ["assets/mermaid.min.js"]
