[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.plantuml]
plantuml-cmd="java -jar /app/plantuml.jar"

[preprocessor.presentation-preprocessor]

[output.html]
additional-css = ["assets/mermaid.css", "assets/print.css"]
additional-js = ["assets/mermaid.min.js", "assets/import-html.js"]
